/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.IOException;

public class App {
    public static void main(String[] args) {

        Person person = new Person();
        person.setName("Vika");
        person.setAge(33);

        // Сериализация объекта в файл
        try {
            person.serializePerson("person.ser");
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Десериализация объекта из файла
        try {
            Person deserializedPerson = Person.deserializePerson("person.ser");
            System.out.println("Десериализованный объект: " + deserializedPerson.getName() + ", " + deserializedPerson.getAge());
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }

        // Сериализация объекта в JSON файл
        person.serializePersonToJson("person.json");
        System.out.println("Объект Person успешно сериализован в JSON");

        // Десериализация объекта из JSON файла
        Person newPerson = Person.deserializePersonFromJson("person.json");
        System.out.println("Десериализованный объект Person:");
        System.out.println("Name: " + newPerson.getName());
        System.out.println("Age: " + newPerson.getAge());
    }

}
